### PR TITLE
Add myself as maintainer

### PR DESCRIPTION
**Pull request by mcs07**

### CODE REVIEW

**Comment by goanpeca** [comment]
@mcs07 now that you are doing this, could you re-render the recipe?

https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock

**Comment by jakirkham** [comment]
Would need a newer re-render, but maybe it is worth merging as is?

**Comment by goanpeca** [comment]
@jakirkham you tell me :-)

**Comment by jakirkham** [comment]
Would just merge it for now. The re-rendering is not that old. Can always re-render again later.

**Pull request merged**
